apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-app
  labels:
    app: prime-app
specs:
  replicas: 2
  selector:
    matchLabels:
      app: prime-app
  template:
    metadata:
      labels:
        app: prime-app
    spec:
      containers:
      - name: prime-app
        image: shubhamp368/amazon-prime-app:latest
        ports:
        - conatainerPort: 3000